name: dart_restaurant_api
description: A server app using the shelf package and Docker.
version: 0.0.1
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  args: ^2.0.0
  equatable: ^2.0.3
  firebase_dart: ^1.0.8
  meta: ^1.8.0
  postgres: ^2.4.3
  shelf: ^1.1.0
  shelf_router: ^1.0.0
  validators: ^3.0.0

dev_dependencies:
  build_runner: ^2.1.11
  build_web_compilers: ^3.2.3
  http: ^0.13.0
  lint: ^1.8.2
  test: ^1.15.0
