name: dart_restaurant_api
description: A server app using the shelf package and Docker.
version: 0.0.1
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  args: ^2.3.1
  collection: ^1.16.0
  crypto: ^3.0.2
  dart_jsonwebtoken: ^2.4.2
  envied: ^0.3.0
  equatable: ^2.0.5
  faker: ^2.0.0
  firebase_dart: ^1.0.11
  jose: ^0.3.2
  meta: ^1.8.0
  postgres: ^2.5.2
  redis: ^3.1.0
  shelf: ^1.4.0
  shelf_router: ^1.1.3
  uuid: ^3.0.6
  validators: ^3.0.0

dev_dependencies:
  build_runner: any
  envied_generator: ^0.3.0
  http: ^0.13.5
  lint: ^2.0.1
